### PR TITLE
Resolve bug not showing plugin repo when no folder is selected

### LINKED ISSUE #15: Plugin Repo Never Loads
When trying to browse available plugins, Swiftbar stays stuck on "Refreshing repository data..."
image

*Systems Details:*
- Intel CPU
- macOS Big Sur 11.1 Beta
- SwiftBar 1.0.1

### PR DESCRIPTION
**Pull request by krubenok**
Closes #15 

- Change title to message so that it's visible in Big Sur
- If no plugin directory is selected when calling repo, ask for a folder

### CODE REVIEW

**Comment by krubenok** [comment]
Could someone please test the directory selection dialogue to ensure that it still shows the "Choose plugin folder" in a pre-Big Sur version of macOS? I don't have a machine handy. (Note the headers of the file windows.)

Before this PR:
image

After this PR:
image

**Comment by melonamin** [comment]
Great work, @krubenok!

> Could someone please test the directory selection dialogue to ensure that it still shows the "Choose plugin folder" in a pre-Big Sur version of macOS? I don't have a machine handy. (Note the headers of the file windows.)

I've checked, works as expected.

```swift
public static func getPlugins() {
    if Preferences.shared.pluginDirectoryPath == nil {
        App.changePluginFolder()
     }
     let preferencesWindowController: NSWindowController?
...
```

I think this only partially addresses the issue:
- it is a little confusing, user clicked "Get Plugins..." and instead received an Open File dialog
- If user presses Cancel in the Open File dialog we end-up in the same situation with the broken Repository Browser

What can we do instead:
- Before presenting the Open File dialog show an alert explaining what is happening
- Check if user pressed Cancel and exit, don't try to show Repository Browser
- or maybe instead just disable "Get Plugins" menu if plugin directory is not set?..

**Comment by krubenok** [comment]
I don't love this while loop but I'm a little too new with Swift to know if there's a more elegant way to detect the cancel on the file picker dialogue and not present the user with the pop-up again without duplicating the code for `changePluginFolder()`. 

```swift
while Preferences.shared.pluginDirectoryPath == nil {
            
            let alert = NSAlert()
            alert.messageText = "Set SwiftBar Plugins Location"
            alert.informativeText = "Select a folder to store the plugins repository"
            alert.addButton(withTitle: "Ok")
            alert.addButton(withTitle: "Cancel")
            let modalResult = alert.runModal()

            switch modalResult {
            case .alertFirstButtonReturn:
                App.changePluginFolder()
            default:
                return
            }
            
        }
```

**Comment by krubenok** [comment]
Edit: this is a little more nuclear way of doing it but now you'd really need to work at it to get past the first run and not set a plugin location. Might be too nuclear for your tastes though...

File: SwiftBar/AppDelegate.swift [hunk 1]
```diff
@@ -7,8 +7,20 @@ class AppDelegate: NSObject, NSApplicationDelegate {
     func applicationDidFinishLaunching(_ aNotification: Notification) {
         //Instance of Plugin Manager must be created after app launch
         pluginManager = PluginManager.shared
-        if Preferences.shared.pluginDirectoryPath == nil {
-            App.changePluginFolder()
+        while Preferences.shared.pluginDirectoryPath == nil {
+            let alert = NSAlert()
+            alert.messageText = "Set SwiftBar Plugins Location"
+            alert.informativeText = "Select a folder to store the plugins repository"
```
Comment (melonamin) [inline SwiftBar/AppDelegate.swift:13]: I suggest to change it to "Select a folder to store the SwiftBar plugins" because in a sense this is what this folder is for.

**Comment by melonamin** [comment]
I like it! 👍 Let me test it and I'll merge
